default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: rails


development:
  <<: *default
  pool: 5
  timeout: 5000
  database: inventory_development
  password: rails_user

test:
  <<: *default
  database: inventory_test
  password: rails_user
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: inventory_production
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
